### ISSUE TITLE
Upload package

### ISSUE THREAD

**Issue by ghost** [felixonmars/dotfiles#1]
Hello Felix,

Can you upload https://github.com/wifiextender/pdf2png/tree/master/C-version to the community, because my aur account doesn't lets me to login. I'd be really grateful if you do this favour for me.

Best regards, Aaron Caffrey

**Comment by felixonmars** [comment]
Hi, this appears to be a low usage package and I do not use it myself, either. Please upload it to the AUR if you are interested.

If you are still experiencing any issues regarding your AUR login, please seek for help on the aur-general mailing list.
